/* eslint import/prefer-default-export: 0 */
export const dataActions = {
  DATA_IS_LOADING: 'DATA_IS_LOADING',
  DATA_ERROR: 'DATA_ERROR',
  DATA: 'DATA'
};

export const contractActions = {
  CONTRACT_IS_LOADING: 'CONTRACT_IS_LOADING',
  CONTRACT_ERROR: 'CONTRACT_ERROR',
  CONTRACT: 'CONTRACT',
  CONTRACT_SET_USER_ADDRESS: 'CONTRACT_SET_USER_ADDRESS'
};

export const serviceActions = {
  SERVICE_IS_LOADING: 'SERVICE_IS_LOADING',
  SERVICE_ERROR: 'SERVICE_ERROR',
  SERVICE: 'SERVICE',
  SERVICE_SET_READY: 'SERVICE_SET_READY',
  SERVICE_LIST_IS_LOADING: 'SERVICE_LIST_IS_LOADING',
  SERVICE_LIST_ERROR: 'SERVICE_LIST_ERROR',
  SERVICE_LIST: 'SERVICE_LIST',
  SERVICE_TRANSACTION_CLEAR: 'SERVICE_TRANSACTION_CLEAR'
};

export const orderActions = {
  ORDER_IS_LOADING: 'ORDER_IS_LOADING',
  ORDER_ERROR: 'ORDER_ERROR',
  ORDER: 'ORDER',
  ORDER_SET_READY: 'ORDER_SET_READY',
  ORDER_LIST_IS_LOADING: 'ORDER_LIST_IS_LOADING',
  ORDER_LIST_ERROR: 'ORDER_LIST_ERROR',
  ORDER_LIST: 'ORDER_LIST',
  ORDER_ACCEPT_IS_LOADING: 'ORDER_ACCEPT_IS_LOADING',
  ORDER_ACCEPT_ERROR: 'ORDER_ACCEPT_ERROR',
  ORDER_ACCEPT: 'ORDER_ACCEPT',
  ORDER_ACCEPT_SET_READY: 'ORDER_ACCEPT_SET_READY',
  ORDER_CANCEL_IS_LOADING: 'ORDER_CANCEL_IS_LOADING',
  ORDER_CANCEL_ERROR: 'ORDER_CANCEL_ERROR',
  ORDER_CANCEL: 'ORDER_CANCEL',
  ORDER_CANCEL_SET_READY: 'ORDER_CANCEL_SET_READY',
  ORDER_COMPLETE_IS_LOADING: 'ORDER_COMPLETE_IS_LOADING',
  ORDER_COMPLETE_ERROR: 'ORDER_COMPLETE_ERROR',
  ORDER_COMPLETE: 'ORDER_COMPLETE',
  ORDER_COMPLETE_SET_READY: 'ORDER_COMPLETE_SET_READY',
  ORDER_RELEASE_IS_LOADING: 'ORDER_RELEASE_IS_LOADING',
  ORDER_RELEASE_ERROR: 'ORDER_RELEASE_ERROR',
  ORDER_RELEASE: 'ORDER_RELEASE',
  ORDER_RELEASE_SET_READY: 'ORDER_RELEASE_SET_READY'
};

export const paymentActions = {
  PAYMENT_IS_LOADING: 'PAYMENT_IS_LOADING',
  PAYMENT_ERROR: 'PAYMENT_ERROR',
  PAYMENT: 'PAYMENT',
  PAYMENT_SET_READY: 'PAYMENT_SET_READY',
  WITHDRAW_IS_LOADING: 'WITHDRAW_IS_LOADING',
  WITHDRAW_ERROR: 'WITHDRAW_ERROR',
  WITHDRAW: 'WITHDRAW',
  WITHDRAW_SET_READY: 'WITHDRAW_SET_READY',
  WITHDRAW_CLEAR: 'WITHDRAW_CLEAR'
};
